server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      

      
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root
  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        highlihjt_sql=true
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      
        
    